### ISSUE TITLE
Restart menu entry error lights

### ISSUE THREAD

**Issue by zephyrus92** [JaGoLi/Libreboot-X200-Updated#11]
The restart menu option is quite buggy. When I press it, it will restart the system; however, the battery and power lights flash indicating an error.

**Comment by JaGoLi** [comment]
Coreboot is quite picky about selecting ram. On some ram sticks, it will boot okay but on reboot it will fail. This seems to be an issue with the coreboot project itself. I will wait for a response from you before closing this issue to see if experimenting with ram will solve the problem for you like it did for me.
