### ISSUE TITLE
em0 disappeared after flashing

### ISSUE THREAD

**Issue by mvhulten** [JaGoLi/Libreboot-X200-Updated#2]
After installing the image, the Intel Ethernet device (em0) disappeared.  The interface is present and works when using the unpatched `libreboot_r20160907_grub_x200_8mb`.

It is the same result with both the FREE rom and the one with the MICROCODE.

In addition, shortly after GrUB and just before the `wsdisplay ...` kernel message, the screen flickers with ![vertical lines](https://user-images.githubusercontent.com/6247934/100890689-69de5900-34b0-11eb-9b62-ba2d51c17e3a.jpg) and stuff.

I am running OpenBSD-current.

**Comment by JaGoLi** [comment]
For solution, see issue #1
