### ISSUE TITLE
function key + f5 no longer disables/enables wifi

### ISSUE THREAD

**Issue by FrostKnight** [JaGoLi/Libreboot-X200-Updated#5]
After updating, I went to disable my wifi card with function key + f5 and it no longer has any effect. If I use rfkill block it will disable it but then function key + f5 doesn't work to enable it. 

Can you fix?

**Comment by JaGoLi** [comment]
This is due to the changes in ACPI in the updated coreboot version. Do activate the kill switch, use xev to find the key pressed by function + f5 and then bind it to a script to disable/enable wifi using a hotkey daemon like xbindkeys.

**Comment by FrostKnight** [comment]
Okay, but I have never used xev before ever...  and when I tried, i had no idea what to do...
