### ISSUE TITLE
ich9gen is a dead tool with known issues - please use the modern bincfg tool from upstream coreboot

### ISSUE THREAD

**Issue by fhvyhjriur** [JaGoLi/Libreboot-X200-Updated#6]
ich9gen should not be used today any more. It creates an IFD with known issues and have other issues that are all fixed in the official coreboot tool named bincfg.
Bincfg can also create the GBE: https://github.com/coreboot/coreboot/blob/master/util/bincfg/Makefile#L15

**Comment by JaGoLi** [comment]
Thank you for suggesting this. I am in the process of updating to coreboot 4.13, and will include the bincfg rom in the new version instead of the one generated with the deprecated ich9gen.

**Comment by fhvyhjriur** [comment]
Maybe you could then rewrite this part here to not point the users to the outdated and partly broken ich9gen tool: https://github.com/JaGoLi/Libreboot-X200-Updated/commit/7cd5f1d222c2fb50fefeb15f5a9fb65c483adefa
